[package]
name = "trie"
version = "0.1.0"

[dependencies]
#MoveStdlib = { git = "https://github.com/starcoinorg/move.git", subdir = "language/move-stdlib", rev = "dev" }
#MoveTableExtension = {git = "https://github.com/starcoinorg/move.git", subdir = "language/extensions/move-table-extension", rev = "dev"}
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "table_extension"}

[dev-addresses]
#Extensions = "0x2"
trie = "0xfc2cd714a9d954dcec4ca5366d2461c4"
[addresses]
trie = "_"
