[package]
name = "trie"
version = "0.1.0"

[dependencies]
MoveStdlib = { git = "https://github.com/starcoinorg/move.git", subdir = "language/move-stdlib", rev = "dev" }
MoveTableExtension = {git = "https://github.com/starcoinorg/move.git", subdir = "language/extensions/move-table-extension", rev = "dev"}
keccak256 = {local="../keccak256"}

[addresses]

Std = "0x1"
Extensions = "0x1"

trie = "_"

[dev-addresses]
trie = "0x42"