[package]
name = "keccak256"
version = "0.1.0"

[dependencies]
MoveStdlib = { git = "https://github.com/starcoinorg/move.git", subdir = "language/move-stdlib", rev = "dev" }

[addresses]

[dev-addresses]
Std =  "0x1"
