on:
  pull_request:
  push:
    branches:
      - main


name: Check and Lint

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./omo
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        working-directory: ./omo
        with:
          profile: minimal
          toolchain: stable
          override: false
      - uses: actions-rs/cargo@v1
        working-directory: ./omo
        with:
          command: check

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./omo
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: false
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        working-directory: ./omo
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: false
      - uses: actions-rs/clippy-check@v1
        working-directory: ./omo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output